#!/usr/bin/env python3
"""Build the full WW2 markdown document for PDF conversion."""

from pathlib import Path

SECTIONS = [
    ("Introduction", """
World War II, fought from 1939 to 1945, was the largest and deadliest conflict in human history. More than thirty nations eventually joined the struggle, and fighting spread across Europe, Africa, Asia, and the world's oceans. Estimates of total deaths range from seventy to eighty-five million people, including soldiers, civilians killed by bombing and occupation, and victims of genocide. The war destroyed cities, displaced millions of families, and overturned political orders that had shaped the nineteenth century.

The conflict did not begin as a single unified war but as a series of aggressive campaigns by authoritarian regimes seeking territory, resources, and racial dominance. Nazi Germany, fascist Italy, and imperial Japan formed the core of the Axis powers. They challenged the liberal democracies of Britain, France, and the United States, as well as the communist Soviet Union. By 1941, the world stood divided between two grand alliances: the Axis and the Allies. Their collision produced industrialized warfare on a scale never seen before.

World War II reshaped the twentieth century in ways that still define international politics. It ended with the collapse of European empires, the division of Germany, the rise of the United States and the Soviet Union as superpowers, and the creation of the United Nations. The Holocaust revealed the horrors of state-sponsored genocide and led to new standards of international law. Atomic weapons introduced an unprecedented threat to human survival. Memory of the war remains central to national identity in countries on every continent.

This document traces the war from its origins in the unresolved tensions of World War I through the major military theaters, the experience of civilians, the crimes committed in the name of ideology, and the diplomatic settlements that followed victory. It examines how technology, intelligence, and industrial production sustained years of total war, and how ordinary people on every home front endured rationing, propaganda, and loss. The narrative moves from the invasion of Poland in September 1939 to the surrender of Japan in August 1945, offering a descriptive account of events, causes, and consequences written for readers who seek both breadth and detail.

The chronological span of six years belies the depth of change within that period. Entire generations came of age knowing only war or occupation. Borders shifted, empires fell, and new superpowers emerged from the rubble of old orders. Civilians learned to read air-raid sirens, families separated by military service adapted to letters and telegrams, and communities rebuilt after bombing with whatever materials remained. The war touched agriculture as farmers were drafted and fields became airfields. It touched culture as artists, writers, and filmmakers documented or resisted the age. No account can name every battle or honor every victim, but a comprehensive narrative can place the largest events in context and explain why they mattered then and matter still.
"""),
    ("Origins and Outbreak of War", """
The roots of World War II lie in the unfinished business of World War I. The Treaty of Versailles, signed in 1919, imposed heavy reparations on Germany, restricted its military, and assigned blame for the war to the German state. Many Germans viewed the treaty as a humiliating "Diktat" imposed by vengeful victors. Economic instability followed. Hyperinflation in the early 1920s wiped out savings, and the Great Depression after 1929 brought mass unemployment. In this climate of fear and resentment, extremist movements gained support by promising national renewal and strong leadership.

Adolf Hitler and the National Socialist German Workers' Party rose to power in January 1933. Hitler dismantled democratic institutions, suppressed opposition, and pursued an aggressive foreign policy aimed at overturning Versailles. He rebuilt the armed forces, remilitarized the Rhineland in 1936, and united Austria with Germany in the Anschluss of 1938. In Munich that same year, Britain and France accepted the German annexation of the Sudetenland from Czechoslovakia in the hope of preserving peace through appeasement. Prime Minister Neville Chamberlain returned to London declaring he had secured "peace for our time," but the agreement only delayed war and encouraged further aggression.

In Italy, Benito Mussolini's fascist regime had come to power earlier, in 1922. Mussolini sought to recreate a Roman-style empire and invaded Ethiopia in 1935. Italy later aligned closely with Germany, though the partnership was often strained by competing ambitions. In Japan, military leaders and nationalist politicians pushed expansion on the Asian mainland. Japanese forces invaded Manchuria in 1931 and launched a full-scale war against China in 1937, demonstrating a pattern of conquest that would eventually draw the Pacific powers into conflict.

The immediate trigger for war in Europe came on September 1, 1939, when German forces invaded Poland. Britain and France, which had guaranteed Polish independence, declared war on Germany on September 3. Soviet troops entered eastern Poland later that month under the secret terms of the Nazi-Soviet Pact. Poland was divided and brutally occupied. Although Britain and France were now at war with Germany, little large-scale fighting occurred on the Western Front during the first months, a period often called the Phony War or Sitzkrieg. The real storm had begun, however, and it would soon sweep across the continent with devastating speed.
"""),
    ("The European Theater (1939-1941)", """
The Phony War ended dramatically in the spring of 1940. Germany launched its offensive in the West on May 10, using fast-moving armored columns and close air support in a strategy known as Blitzkrieg, or lightning war. Dutch and Belgian defenses were overrun, and German forces bypassed the heavily fortified Maginot Line by advancing through the Ardennes forest into France. Allied armies, including large British and French formations, were encircled and destroyed or captured. The evacuation of more than three hundred thousand soldiers from Dunkirk in late May and early June saved Britain's army but left France facing collapse.

France signed an armistice on June 22, 1940. Germany occupied northern and western France, while the southeastern portion became a collaborationist state governed from Vichy under Marshal Philippe Petain. Britain now stood alone against Germany in Western Europe. Hitler turned to air power to soften Britain for invasion. From July to October 1940, the Royal Air Force fought the Luftwaffe in the Battle of Britain. German bombers attacked cities, including London during the Blitz, but failed to destroy RAF fighter defenses or break British morale. The planned invasion of Britain, Operation Sea Lion, was never carried out.

In North Africa and the Mediterranean, Italy and Britain struggled for control of vital shipping routes. Italian offensives from Libya into Egypt faltered, and British forces under commanders such as General Archibald Wavell pushed back. Germany later sent the Afrika Korps under General Erwin Rommel to support its ally. The desert war swung back and forth across Libya and Egypt until Allied victory at El Alamein in late 1942, though that decisive phase belongs partly to the later Western Front narrative.

The most consequential opening of a new front came on June 22, 1941, when Germany launched Operation Barbarossa, the invasion of the Soviet Union. More than three million Axis soldiers advanced along a vast front. Hitler expected a quick victory, but Soviet resistance, harsh terrain, and the brutal winter slowed the advance. Leningrad was encircled and subjected to a siege that would last nearly nine hundred days. German forces reached the outskirts of Moscow in late 1941 but failed to capture the capital. In the south, they pushed toward the oil fields of the Caucasus and the industrial city of Stalingrad on the Volga River. By the end of 1941, the European war had expanded into the largest land conflict the world had ever seen.
"""),
    ("The Pacific Theater", """
Japanese expansion in Asia long preceded the attack on Pearl Harbor. Japan, an island nation dependent on imported raw materials, sought economic self-sufficiency and regional dominance. After invading Manchuria in 1931, Japan established the puppet state of Manchukuo. Full-scale war with China began in 1937, bringing atrocities such as the Nanjing Massacre and years of brutal occupation. Western powers, including the United States, Britain, and the Netherlands, controlled colonies and resources across Southeast Asia. Japanese leaders viewed these territories as obstacles to their empire and as vulnerable once Europe became consumed by war against Germany.

American policy responded with economic pressure. The United States imposed embargoes on oil and other strategic materials essential to Japan's war machine. Negotiations in 1941 failed to resolve the standoff. On December 7, 1941, Japan struck without warning at the U.S. naval base at Pearl Harbor in Hawaii, sinking or damaging numerous warships and killing more than two thousand American servicemen. Hours later, Japanese forces attacked British Malaya, Hong Kong, Guam, and the Philippines. Germany and Italy declared war on the United States, and the conflict became truly global.

The first months of the Pacific war brought a string of Japanese victories. Singapore fell in February 1942 in one of the greatest Allied defeats in history. The Philippines, Dutch East Indies, and Burma were overrun. Allied navies suffered heavy losses, but two carrier battles in 1942 began to shift momentum. At the Coral Sea in May, American and Australian forces fought Japan to a tactical draw and prevented a landing at Port Moresby. At Midway in June, U.S. Navy carriers destroyed four Japanese fleet carriers in a decisive victory that ended Japan's unchecked expansion.

The long campaign to roll back Japanese gains began with Guadalcanal in the Solomon Islands, where U.S. Marines landed in August 1942. Months of ferocious land, sea, and air fighting secured the island by early 1943. Allied strategy in the Pacific, led by Admiral Chester Nimitz in the central Pacific and General Douglas MacArthur in the southwest, combined island-hopping amphibious assaults with submarine warfare against Japanese shipping. As Allied forces advanced toward the Japanese home islands, Japan increasingly relied on kamikaze suicide pilots and prepared for a final defensive struggle that would prove extraordinarily costly for both sides.
"""),
    ("The Eastern Front", """
The war between Nazi Germany and the Soviet Union was the central military struggle of World War II in Europe. It absorbed the majority of German land forces and produced casualties on a scale unmatched elsewhere. Hitler's invasion was driven by ideological hatred of communism, desire for Lebensraum (living space), and belief in the racial inferiority of Slavic peoples. German planning assumed the Soviet state would collapse within weeks. Instead, the Red Army, despite catastrophic early losses, mobilized industry beyond the Ural Mountains and fought with growing effectiveness.

The turning point on the Eastern Front is widely identified with the Battle of Stalingrad, which raged from August 1942 to February 1943. Control of the city named for Stalin carried symbolic and strategic importance. Street-by-street fighting reduced much of Stalingrad to rubble. In November 1942, Soviet forces under General Georgy Zhukov launched Operation Uranus, encircling the German Sixth Army under Field Marshal Friedrich Paulus. Hitler forbade retreat, and the trapped army surrendered in February 1943. Roughly one hundred thousand German soldiers entered captivity; few would return home. Stalingrad shattered the myth of German invincibility and marked the beginning of a sustained Soviet offensive.

In July 1943, Germany launched its last major offensive in the east at Kursk, hoping to regain initiative with a massive tank battle. Soviet defenses, strengthened by intelligence and prepared positions, blunted the attack. After Kursk, the Red Army held the strategic advantage for the remainder of the war. Partisan movements behind German lines in Belarus, Ukraine, and the Baltic states harassed supply columns and garrisons, often at terrible cost to civilian populations caught between occupiers and resistance fighters.

Operation Bagration in the summer of 1944 destroyed German Army Group Center and liberated Belarus in a rapid advance. Soviet forces then pushed through Poland toward the Vistula and eventually reached the Oder River, less than sixty miles from Berlin. Civilian suffering on the Eastern Front was immense. Occupation policies included mass shootings, starvation, deportation for forced labor, and destruction of villages suspected of supporting partisans. The Red Army's advance into Germany in 1945 was accompanied by widespread violence against civilians, a grim counterpart to earlier German atrocities. Berlin fell in May 1945 after a brutal urban battle, and Germany surrendered unconditionally.
"""),
    ("The Western Front and Italy", """
While the Eastern Front consumed the bulk of German manpower, the Western Allies opened new fronts that squeezed the Third Reich from the west and south. After victory at El Alamein in November 1942, British forces under General Bernard Montgomery pursued Rommel's Afrika Korps westward. American troops landed in Morocco and Algeria during Operation Torch in November 1942, trapping Axis forces in Tunisia. The surrender of Axis armies in North Africa in May 1943 removed the threat to Egypt and opened the Mediterranean to Allied use.

Allied leaders then turned to Sicily and Italy. The invasion of Sicily in July 1943 led to the fall of Mussolini and Italy's eventual surrender, though German troops continued to resist fiercely on the Italian peninsula. The campaign up Italy's mountainous spine proved slow and costly, tying down Allied divisions that some commanders wished to deploy elsewhere. Rome was liberated in June 1944, but fighting continued until the war's end in northern Italy.

The decisive Western Front operation began on June 6, 1944: D-Day, or Operation Overlord. Under Supreme Allied Commander General Dwight D. Eisenhower, American, British, Canadian, and other Allied forces crossed the English Channel and landed on the beaches of Normandy in the largest amphibious invasion in history. Paratroopers dropped behind German lines, naval guns pounded coastal defenses, and soldiers fought through minefields and fortified positions at Utah, Omaha, Gold, Juno, and Sword beaches. After securing the beachhead, Allied armies broke out of Normandy in late July and liberated Paris by August.

The advance across France and the Low Countries slowed in the autumn due to supply shortages and stiffening German resistance. In December 1944, Germany launched a surprise counteroffensive in the Ardennes, known as the Battle of the Bulge. American units fought desperate defensive actions in freezing weather before Allied reinforcements and air power restored the front. In the spring of 1945, Allied armies crossed the Rhine and swept into western Germany. Soviet and Western forces converged on Berlin from east and west. Germany signed unconditional surrender on May 8, 1945, marking Victory in Europe Day. The Western Front had complemented the Soviet drive and ensured that Nazi Germany faced overwhelming force on every side.
"""),
    ("War in Asia and the Atomic End", """
Allied campaigns in Asia outside the central Pacific involved vast distances, disease, and determined Japanese resistance. In Burma, British, Indian, Chinese, and later American forces fought to reopen supply routes to China and to prevent Japanese advance toward India. The Burma Road and the air route over "the Hump" of the Himalayas supplied Chinese armies under General Chiang Kai-shek, who had been at war with Japan since 1937. Chinese resistance tied down large numbers of Japanese troops, though internal conflict between Nationalists and Communists weakened unified effort.

In the Pacific, island campaigns grew increasingly fierce as Allied forces neared Japan. Battles at Tarawa, Saipan, Iwo Jima, and Okinawa demonstrated Japanese willingness to fight to the last man rather than surrender. American casualties mounted, and civilian casualties on Okinawa underscored the human cost of invasion. From late 1944, U.S. B-29 Superfortress bombers struck Japanese cities from bases in the Mariana Islands. Incendiary raids created firestorms that destroyed urban areas and killed tens of thousands of civilians. Tokyo suffered particularly devastating attacks in March 1945.

Meanwhile, the Manhattan Project, a massive secret American and British scientific effort, had developed atomic weapons. President Harry S. Truman, who had succeeded Franklin D. Roosevelt after the president's death in April 1945, faced the decision of whether to use the new bomb against Japan. Advocates argued that an invasion of the Japanese home islands would cost enormous American and Japanese lives. Critics, then and since, have questioned the military necessity and moral justification of nuclear attack on cities.

On August 6, 1945, an American B-29 named Enola Gay dropped an atomic bomb on Hiroshima, killing tens of thousands instantly and many more from radiation and injuries. A second bomb devastated Nagasaki on August 9. The Soviet Union declared war on Japan and invaded Manchuria the same day. Emperor Hirohito announced Japan's surrender on August 15, and formal surrender documents were signed aboard the USS Missouri in Tokyo Bay on September 2, 1945. World War II had ended, but the atomic age had begun, altering strategic thinking and international relations for generations.
"""),
    ("The Holocaust and Crimes Against Humanity", """
The Holocaust was the systematic, state-sponsored murder of six million Jews by Nazi Germany and its collaborators. It stands as the defining crime of World War II and one of the darkest chapters in human history. Nazi racial ideology classified Jews as an existential enemy of the German people and sought their complete elimination. This goal was not a byproduct of war but a central purpose of Hitler's regime, pursued with bureaucratic efficiency and industrial methods.

Persecution escalated in stages. The Nuremberg Laws of 1935 stripped Jews of citizenship and civil rights. Kristallnacht in November 1938 saw coordinated attacks on synagogues, businesses, and homes across Germany and Austria. After war began, ghettos such as those in Warsaw and Lodz confined Jewish populations in overcrowded, starving conditions. Mobile killing units called Einsatzgruppen followed the German army into the Soviet Union, shooting hundreds of thousands of Jews and others in mass pits at Babi Yar and countless other sites.

The "Final Solution" evolved toward extermination camps equipped with gas chambers and crematoria. Auschwitz-Birkenau in occupied Poland became the largest killing center, where more than one million Jews were murdered, along with Roma, Soviet prisoners, and others. Camps including Treblinka, Sobibor, Belzec, and Chelmno operated as dedicated death factories. Deportations from across Europe fed the machinery of genocide. Trains arrived from France, the Netherlands, Greece, Hungary, and many other countries, often with victims unaware of their fate until the last moments.

Resistance occurred in ghettos, forests, and camps, including the Warsaw Ghetto Uprising of 1943. Survivors bore witness after liberation, and Allied forces documented horrors as they entered camps in 1945. The Nuremberg trials prosecuted leading Nazi officials for crimes against peace, war crimes, and crimes against humanity. The Holocaust established precedents for international humanitarian law and the principle that individuals, not only states, could be held accountable for atrocities. Its legacy demands remembrance, education, and vigilance against hatred and genocide in every era.
"""),
    ("The Home Front", """
Total war transformed societies far from the front lines. Governments mobilized economies for military production, regulated prices and wages, and rationed food, fuel, and consumer goods. Propaganda campaigns urged sacrifice, unity, and hatred of the enemy. On the Allied side, Britain endured the Blitz and maintained morale through the leadership of Prime Minister Winston Churchill and the shared hardship of blackout conditions and ration books. The United States converted factories to produce ships, aircraft, tanks, and ammunition at a scale that dwarfed Axis output. Rosie the Riveter became a symbol of women entering industrial jobs in unprecedented numbers.

Women served in auxiliary military branches such as the Women's Army Corps, worked in agriculture and transport, and staffed hospitals and codebreaking facilities. In the Soviet Union, women fought in combat roles, including as snipers and pilots in all-female air regiments. Axis home fronts faced increasing strain as the war turned against Germany and Japan. Allied bombing of German and Japanese cities destroyed housing and infrastructure, disrupted production, and killed civilians, though debate continues over the strategic effect and ethical implications of area bombing.

Occupied nations experienced the war as exploitation and terror. Food was seized, laborers were deported, and resistance networks formed underground. In France, the Vichy regime collaborated with German authorities until liberation. Poland lost a higher percentage of its population than almost any other country. Neutral states such as Switzerland and Sweden navigated complex relationships with belligerents, providing banking, trade, or refuge under conditions that historians continue to scrutinize.

Displacement affected millions. Refugees fled advancing fronts, bombed cities, and ethnic cleansing. At war's end, millions of displaced persons wandered Europe, including survivors of camps and forced laborers unable to return home. The home front was not a place of safety but a sphere where ordinary people endured fear, loss, and transformation. Their labor and endurance sustained the armies that ultimately defeated the Axis powers.
"""),
    ("Technology, Intelligence, and Innovation", """
World War II accelerated technological change across nearly every field of engineering and science. Tanks and self-propelled guns became central to ground combat, with models such as the German Panther, Soviet T-34, and American Sherman representing advances in armor, mobility, and firepower. Aircraft evolved from biplanes of the interwar years to long-range bombers and fast fighters. The Spitfire, Messerschmitt Bf 109, P-51 Mustang, and Zero became icons of air warfare. Aircraft carriers replaced battleships as the decisive naval weapon in the Pacific.

Submarines nearly strangled Britain's Atlantic supply lines in 1942 before improved convoy tactics, long-range aircraft, and codebreaking turned the Battle of the Atlantic in the Allies' favor. Radar and sonar enhanced detection of enemy ships and aircraft. The German V-1 flying bomb and V-2 rocket introduced new dimensions of long-range attack on civilian targets and foreshadowed postwar missile development.

Intelligence and codebreaking proved as vital as any weapon. At Bletchley Park in Britain, mathematicians and linguists including Alan Turing worked to break German Enigma cipher machines. Ultra intelligence, derived from decrypted German communications, helped Allied commanders anticipate U-boat movements and German operational plans. American codebreakers achieved similar successes against Japanese naval codes, contributing to victories at Midway and elsewhere. Deception operations such as Operation Bodyguard misled Germany about the location and timing of the Normandy invasion.

Medical advances, often driven by military necessity, included widespread use of antibiotics such as penicillin, improved surgical techniques for trauma, and blood plasma transfusion. The war also produced horrific applications of science, including medical experiments in Nazi camps and Japanese Unit 731. Jet engines, helicopters, and electronic computing emerged from wartime research programs. The atomic bomb represented the ultimate fusion of scientific discovery and military demand. Technology did not determine the war's outcome alone, but nations that mobilized innovation effectively gained decisive advantages on land, at sea, and in the air.
"""),
    ("Diplomacy and the Grand Alliance", """
The alliance that defeated the Axis was united by necessity rather than shared ideology. Britain, the Soviet Union, and the United States cooperated despite deep mistrust between communism and capitalism. The Atlantic Charter of August 1941, issued by Churchill and Roosevelt, outlined war aims including self-determination, economic cooperation, and disarmament of aggressor nations. It provided a moral framework for the Allied cause even before the United States entered the war.

Summit conferences shaped strategy and postwar planning. At Tehran in November 1943, Roosevelt, Churchill, and Stalin confirmed the opening of the Second Front in France and discussed the future of Poland and Germany. At Yalta in February 1945, with victory in sight, the Big Three agreed on zones of occupation in Germany, Soviet entry into the war against Japan, and the framework for a United Nations organization. Critics later argued that Roosevelt conceded too much to Stalin regarding Eastern Europe, though Soviet military presence on the ground limited Western leverage.

The Potsdam Conference in July and August 1945, attended by Truman, Churchill (later Clement Attlee), and Stalin, addressed the administration of defeated Germany and the terms of Japanese surrender. Tensions visible at Potsdam reflected the emerging Cold War. The Grand Alliance dissolved quickly after victory as ideological rivalry replaced common enemies.

The United Nations was founded in San Francisco in June 1945 to prevent future global wars through collective security and international cooperation. Its charter built on lessons of the failed League of Nations while granting permanent Security Council veto power to major victors. Diplomacy during World War II thus shaped not only military outcomes but the institutional architecture of the postwar world, balancing ideals of self-determination and human rights against great-power competition that would dominate the second half of the twentieth century.
"""),
    ("Aftermath and Legacy", """
Victory in 1945 left a world transformed and deeply wounded. Military deaths numbered in the tens of millions, and civilian deaths from bombing, famine, occupation, and genocide raised the total far higher. The Soviet Union suffered the heaviest losses, with an estimated twenty-seven million dead. Poland, Yugoslavia, and Germany experienced devastation of cities and populations. Japan's home islands endured firebombing and nuclear attack. Families across every continent mourned the missing and rebuilt shattered communities.

Germany was divided into occupation zones controlled by the United States, Britain, France, and the Soviet Union. Berlin, located within the Soviet zone, was itself partitioned. The Nuremberg trials established that leaders could be prosecuted for planning aggressive war and atrocities. Japan underwent American-led occupation under General MacArthur, adopted a pacifist constitution, and eventually became a democratic ally of the West. The experience of defeat and occupation shaped national memory in both former Axis powers.

The Cold War began almost immediately as the wartime alliance collapsed. Soviet control of Eastern Europe, symbolized by the Iron Curtain described by Churchill in 1946, confronted American commitment to contain communism. The division of Germany hardened into two states: the Federal Republic of Germany in the west and the German Democratic Republic in the east. Berlin became a flashpoint, culminating in the blockade of 1948-1949 and the construction of the Berlin Wall in 1961.

European empires weakened by war faced rising demands for independence in Asia, Africa, and the Middle East. Decolonization reshaped the global map in the decades after 1945. The United States and Soviet Union competed for influence in the developing world, exporting rival models of political and economic organization. Memory of World War II remains contested. Memorials, museums, and anniversaries preserve sacrifice and suffering. Historians debate decisions such as strategic bombing, the timing of the Second Front, and the use of atomic weapons. The war's legacy is not confined to the past; it continues to inform discussions of nationalism, alliance, human rights, and the responsibilities of power in an interconnected world.
"""),
]

EXPANSIONS = {
    "Introduction": """
Key leaders shaped the course of the conflict. Winston Churchill rallied Britain with eloquent speeches that promised blood, toil, tears, and sweat while refusing compromise with Hitler. Franklin D. Roosevelt guided the United States from isolationism toward full participation as the Arsenal of Democracy. Joseph Stalin commanded the Soviet Union through invasion and catastrophic losses toward eventual triumph. Adolf Hitler's strategic overreach, including the invasion of the Soviet Union and declaration of war on the United States, contributed decisively to Germany's defeat. The war's geography spanned the Arctic convoys to Murmansk, the sands of El Alamein, the jungles of Burma, and the coral atolls of the Pacific. Each theater demanded different tactics, climates, and logistics, yet all were linked by global alliance systems and the industrial capacity to sustain years of attrition.

Historians classify World War II as a total war because nations mobilized every resource, blurring the line between combatants and civilians. Children collected scrap metal; scientists built weapons; filmmakers produced propaganda. Neutrality became difficult to maintain as belligerents demanded alignment or access. The war accelerated social change, including expanded roles for women and minorities in industry and military service, even where discrimination persisted. Its end left unresolved questions about colonialism, racial justice, and the moral limits of warfare that societies continue to address decades later.
""",
    "Origins and Outbreak of War": """
The League of Nations, created after World War I to preserve peace, proved unable to stop aggression. Japan's conquest of Manchuria and Italy's invasion of Ethiopia exposed the organization's weakness. When Germany remilitarized the Rhineland, Britain and France did not intervene militarily. The Spanish Civil War from 1936 to 1939 served as a testing ground for German and Italian arms and tactics, while Britain, France, and the Soviet Union supported the Republican side in limited ways. The Nazi-Soviet Pact of August 1939 shocked the world because it united ideological enemies, but it allowed Hitler to attack Poland without immediate fear of a two-front war. Poland's cavalry, infantry, and air force fought bravely but could not withstand combined German and Soviet assault. The city of Warsaw endured heavy bombing before surrendering in late September. For Poles, the war would not end in 1945, as Soviet domination followed German defeat.

Historians continue to debate whether more resolute action against early Axis aggression could have prevented world war. What is clear is that economic depression, nationalist grievance, and faith in military solutions created a combustible international order. The failure of democracies to coordinate deterrence, combined with Soviet strategic calculations, gave authoritarian leaders confidence that expansion would meet limited resistance until it was too late to stop them without global conflict.
""",
    "The European Theater (1939-1941)": """
Winston Churchill became prime minister during the crisis of May 1940 and embodied British defiance. His partnership with Roosevelt, strengthened by the Lend-Lease program supplying American material to Britain, sustained the island nation until the United States entered the war. The Arctic convoys delivering supplies to the Soviet Union and the Battle of the Atlantic protecting merchant shipping were essential but often overlooked campaigns. On the Eastern Front, the siege of Leningrad caused more than one million deaths from starvation, shelling, and disease, yet the city did not surrender. The defense of Moscow in December 1941, aided by fresh Siberian divisions and severe cold, marked the first major German failure in Barbarossa. General Erwin Rommel earned the nickname Desert Fox for bold maneuvers in North Africa, but even his skill could not compensate for chronic fuel shortages and Allied numerical superiority that would emerge in later years.

The period from 1939 to 1941 established patterns that would persist until defeat: German reliance on rapid offensives, Allied adaptation through intelligence and industrial depth, and civilian endurance under bombardment. By December 1941, Germany faced war against Britain, the Soviet Union, and indirectly the full economic weight of the United States. Hitler's decision to declare war on America after Pearl Harbor closed the last possibility of a limited European conflict and ensured that Allied resources would eventually overwhelm Axis production.
""",
    "The Pacific Theater": """
General Douglas MacArthur, forced to evacuate the Philippines with the promise to return, became a symbol of Allied determination in the southwest Pacific. Admiral Chester Nimitz directed central Pacific operations with methodical amphibious assaults on chains of islands leading toward Japan. The Doolittle Raid of April 1942, launching bombers from the carrier Hornet to strike Tokyo, boosted American morale after Pearl Harbor despite limited material damage. Australian and New Zealand forces defended their territories and contributed to campaigns in New Guinea. The Battle of the Philippine Sea in 1944, sometimes called the Great Marianas Turkey Shoot, destroyed Japanese naval air power on a scale from which Japan never recovered. Submarines such as those operating from Pearl Harbor sank a large fraction of Japanese merchant shipping, strangling the home islands of oil, food, and raw materials long before soldiers set foot on Japanese soil.

The Pacific war was fought across enormous ocean distances with specialized amphibious doctrine and carrier aviation at its center. Japan's initial advantage in experience and morale eroded as Allied training, logistics, and production surpassed Japanese capacity to replace ships, aircraft, and trained pilots. Cultural expectations on both sides influenced conduct in battle, including Japanese reluctance to surrender and Allied adaptation to costly assaults on fortified islands. Understanding the Pacific theater is essential to grasping why the war against Japan ended with such destructive air and naval power rather than a conventional invasion alone.
""",
    "The Eastern Front": """
The scale of the Eastern Front defies easy comparison. Entire armies of hundreds of thousands were encircled and destroyed in operations at Kiev, Vyazma, and elsewhere during 1941. German occupation policies treated Slavs as subhuman and deliberately starved prisoners of war by the millions. The Warsaw Uprising of 1944, launched by the Polish Home Army as Soviet forces approached, was crushed after sixty-three days while the Red Army halted on the far bank of the Vistula, a source of lasting bitterness in Poland. The Battle of Berlin in April and May 1945 pitted more than two million Soviet troops against desperate German defenders, including elderly men and boys from the Volkssturm militia. Hitler committed suicide in his bunker on April 30, and surrender followed within days. The Eastern Front accounted for roughly eighty percent of German military deaths, confirming its status as the primary arena of Germany's destruction.

Weather, mud, and vast distances shaped operations as much as generalship. Rasputitsa, the season of rain and thaw, turned roads into quagmires that stalled tanks and supply trucks. Winter favored defenders who understood the climate and could operate in extreme cold. Soviet industry, relocated eastward on railroad flatcars, produced tanks and artillery that eventually surpassed German quality and quantity in key categories. The human cost on both sides reflected a war of annihilation in which ideological hatred reduced willingness to accept compromise or humane treatment of prisoners and civilians.
""",
    "The Western Front and Italy": """
Operation Overlord required years of planning, deception, and buildup. Fake armies under General George Patton in southeastern England misled German intelligence about the landing site. Mulberry artificial harbors and Pluto undersea pipelines supplied forces in Normandy after D-Day. The hedgerow country of Normandy slowed Allied advance until Operation Cobra broke through near Saint-Lo in July 1944. Liberation brought joy but also reckoning, as communities punished collaborators and confronted the discovery of camps and hidden atrocities. Operation Market Garden in September 1944, an ambitious airborne attempt to seize bridges in the Netherlands, failed to cross the Rhine at Arnhem and delayed further advance. The Rhine crossing at Remagen in March 1945 exploited a bridge captured before demolition, accelerating the final drive into Germany. Meeting at the Elbe River in April, American and Soviet soldiers celebrated together even as political mistrust already shadowed the alliance.

The Italian campaign tied down German divisions but at a price in time and casualties that Allied commanders disputed throughout 1943 and 1944. Anzio's landing threatened Rome but stalled in stalemate before breakout. Monte Cassino's monastery, destroyed by Allied bombing, became a symbol of the campaign's difficulty. In northwest Europe, logistics often constrained advance as fuel and ammunition raced to keep pace with fast-moving armies. The Western Front nevertheless ensured that Germany could not concentrate solely against the Soviet Union, fulfilling the strategic purpose of the Second Front that Stalin had demanded since 1941.
""",
    "War in Asia and the Atomic End": """
The battle for Iwo Jima in February 1945 produced the iconic image of Marines raising the flag on Mount Suribachi, yet the fighting continued for weeks and cost nearly seven thousand American lives. Okinawa, the largest amphibious assault in the Pacific, lasted from April to June 1945 and saw ferocious kamikaze attacks on Allied ships. Japanese civilians on Okinawa suffered heavily, including many directed by propaganda to resist rather than surrender. The planned invasion of Japan, Operation Downfall, would have involved massive landings on Kyushu and Honshu. Estimates of Allied casualties ran into the hundreds of thousands, motivating Truman's advisers who supported using the atomic bomb. Hiroshima and Nagasaki were chosen in part for their military and industrial significance. Debate over whether Japan would have surrendered without nuclear attack continues among historians, but the emperor's intervention against military hardliners was decisive in accepting surrender after the second bomb and Soviet invasion.

China's war with Japan predated European conflict by years and continued until 1945, making it one of the longest struggles of the era. The rivalry between Chiang Kai-shek's Nationalists and Mao Zedong's Communists weakened unified resistance but both continued fighting Japanese occupation. In Southeast Asia, colonial territories fell to Japan and later became crucibles of nationalist movements. The atomic bombings remain among the most studied decisions in military history, raising enduring questions about civilian targeting, deterrence, and the ethics of weapons of mass destruction in an age when nuclear arsenals still shape global security.
""",
    "The Holocaust and Crimes Against Humanity": """
Roma and Sinti peoples, disabled persons, political opponents, Jehovah's Witnesses, and Soviet prisoners of war were also targeted for murder or brutal treatment. Auschwitz combined slave labor with extermination; prisoners who were not gassed immediately often died from disease, starvation, or exhaustion. Sonderkommandos, prisoners forced to work in the gas chambers and crematoria, staged revolts including one that destroyed a crematorium at Auschwitz-Birkenau in October 1944. International responses before and during the war were widely criticized as inadequate. Evian Conference of 1938 failed to produce refuge for Jews fleeing Nazism. Reports of mass killing reached Allied governments, but priority remained defeating Germany militarily. After liberation, displaced persons camps housed survivors who could not or would not return to hometowns where neighbors had collaborated or where all family had perished. The phrase "Never Again" emerged from this history, though subsequent genocides have shown how difficult prevention remains.

Crimes against humanity extended beyond the Holocaust. Japanese forces committed atrocities including the Nanjing Massacre and brutal treatment of prisoners of war on the Burma Railway. Unit 731 conducted biological experiments on captives in Manchuria. Forced labor programs deported millions from occupied Europe to work in German industry and agriculture under deadly conditions. Understanding these crimes separately from conventional military violence is essential to historical accuracy and to honoring victims whose suffering must not be minimized or conflated with other wartime hardships.
""",
    "The Home Front": """
In the United States, Executive Order 9066 authorized the internment of Japanese Americans, a grave violation of civil liberties later acknowledged by official apology and reparations. Black Americans served in segregated units and returned to demand full citizenship rights, fueling the postwar civil rights movement. Britain's children were evacuated from cities during the Blitz, and families grew victory gardens to supplement rations. Germany's home front initially benefited from conquests that brought looted food and goods, but Allied bombing of Hamburg, Dresden, and other cities created firestorms and widespread destruction. Albert Speer's organization of war production prolonged German resistance longer than many expected. Japan's home front endured increasing hunger as submarine blockade tightened; schoolchildren were mobilized to factory work and civilians trained with bamboo spears in anticipation of invasion. Resistance movements in Yugoslavia under Josip Broz Tito, in France under Jean Moulin's coordinated networks, and in Poland's Home Army demonstrated that occupation did not mean acceptance.

Broadcast radio and newsreels shaped public perception on every side, celebrating victories and concealing defeats when possible. Churchill's speeches and Roosevelt's fireside chats maintained civilian commitment to long wars. Axis propaganda emphasized racial superiority and enemy vilification until shortages and bombing undermined credibility. The home front thus was both a source of strength and a mirror of each nation's values, inequalities, and capacity to endure sacrifice over years rather than months.
""",
    "Technology, Intelligence, and Innovation": """
The Liberty ship program in American shipyards produced cargo vessels faster than German submarines could sink them once Allied escort groups and air cover improved. The P-51 Mustang, fitted with long-range drop tanks, escorted bombers deep into Germany and decimated the Luftwaffe in 1944. Radar-equipped night fighters and coastal defenses reduced the U-boat threat. German jet fighters such as the Me 262 arrived too late and in too few numbers to change air superiority. The Enigma machine was not the only German cipher; Colossus computers at Bletchley Park helped break Lorenz teleprinter codes used by Hitler's high command. Navajo code talkers in the U.S. Marine Corps used their language for secure battlefield communications in the Pacific. Penicillin mass production saved countless wounded soldiers from infection. Blood banks and mobile surgical units improved survival rates. Rockets, jets, and nuclear energy passed from wartime laboratories into Cold War arsenals and civilian industry.

Amphibious landing craft such as the Higgins boat enabled invasions from Normandy to the Pacific atolls. Bailey bridges allowed armies to cross rivers under fire. Synthetic rubber and fuel production freed Allied nations from dependence on captured territories. Each innovation reflected the lesson that modern war rewards societies that integrate science, industry, and training into a unified effort. Axis powers achieved notable technical successes but could not match Allied scale of production and coordination across multiple theaters simultaneously.
""",
    "Diplomacy and the Grand Alliance": """
The Casablanca Conference of January 1943 declared the Allied demand for unconditional surrender of the Axis, signaling that no negotiated peace would preserve Hitler's regime. Stalin repeatedly pressed for a Second Front to relieve pressure on the Soviet Union; Churchill favored Mediterranean operations before Normandy. The Polish question poisoned relations between the Western Allies and the Soviet Union throughout the war. At Yalta, Poland's borders were shifted westward, and a communist-dominated government eventually took power despite promises of free elections. The Morgenthau Plan proposing deindustrialization of Germany was rejected in favor of reconstruction, though Potsdam authorized removal of industrial equipment as reparations. The United Nations replaced the League with broader membership and a Security Council including the United States, Soviet Union, Britain, China, and France. Specialized agencies such as UNESCO and the World Bank grew from wartime discussions about lasting peace and economic stability.

Personal relationships among leaders influenced diplomacy as much as formal agreements. Roosevelt's optimism about managing Stalin contrasted with Churchill's early anti-Soviet instincts. Stalin's suspicion of Western delay in opening the Second Front persisted despite eventual Overlord. French leader Charles de Gaulle fought for recognition of Free France in Allied councils. Diplomacy during the war therefore combined high ideals with hard bargains over territory, influence, and the future of nations whose fate was decided in part without their participation at the conference table.
""",
    "Aftermath and Legacy": """
The Marshall Plan from 1948 aided Western European recovery and strengthened democratic institutions against communist influence. West Germany's economic miracle under Chancellor Konrad Adenauer integrated the country into NATO and the European community. East Germany remained under Soviet-style rule until reunification in 1990. War crimes trials in Tokyo prosecuted Japanese leaders, though Emperor Hirohito was not tried, a decision that remains controversial. Veterans returned to build postwar societies; many carried physical and psychological wounds. The term "Holocaust" entered widespread use as survivors published memoirs and historians documented the genocide systematically. Museums such as Yad Vashem in Israel, the United States Holocaust Memorial Museum in Washington, and memorials at Auschwitz preserve testimony for future generations. Films, literature, and anniversaries of D-Day, VE Day, and VJ Day keep public memory alive. World War II set precedents for humanitarian intervention, war crimes prosecution, and international cooperation, even when later conflicts tested those ideals severely.

The war's demographic impact included millions of widows, orphans, and disabled veterans requiring decades of social adjustment. Birth rates shifted as soldiers returned home. Borders drawn or confirmed at war's end displaced ethnic populations in Central and Eastern Europe through forced migration that redrew the region's national composition. Israel's founding in 1948 connected in part to Holocaust trauma and displaced Jewish populations seeking refuge. Asia's political map similarly transformed as independence movements ended European colonial rule in India, Indonesia, Indochina, and Africa in succeeding decades. World War II therefore did not merely end in 1945; it launched the political, social, and technological world we inhabit today.
""",
}


CONCLUSION = """
## Conclusion

World War II stands as the defining catastrophe and turning point of the twentieth century. Its origins lay in unresolved grievances from the First World War, economic collapse, and the rise of aggressive ideologies that rejected democracy and human equality. From the invasion of Poland in 1939 to the surrender ceremonies aboard the USS Missouri in 1945, the conflict unfolded across continents and oceans with a ferocity made possible by industrial civilization itself. Nations that had built railways, radios, and assembly lines turned those capacities toward mass destruction on a scale that earlier generations could scarcely have imagined.

The military narrative alone cannot capture the war's full meaning. Behind every campaign were millions of individuals: soldiers who endured mud, heat, and fear; sailors who crossed submarine-infested seas; airmen who flew missions knowing many would not return; civilians who hid in shelters, worked night shifts in factories, or hid neighbors from deportation at risk of their own lives. The Holocaust demonstrated that modern bureaucracy and technology could serve murder as efficiently as they served production. Resistance and rescue, though they could not prevent genocide, proved that moral choice remained possible even under tyranny.

Allied victory resulted from combined factors rather than a single advantage. Soviet sacrifice on the Eastern Front destroyed the bulk of German military power. Western economic strength and naval control supplied material that Axis nations could not match once the war became prolonged. Intelligence breakthroughs saved lives and shortened campaigns. Leadership at critical moments, from Churchill's refusal to negotiate in 1940 to Roosevelt's mobilization of American industry, sustained hope when defeat seemed possible. Yet victory came at a price so high that celebration was always tempered by grief.

The war's end did not bring universal peace. The Cold War divided Europe and threatened nuclear annihilation. Decolonization reshaped Asia and Africa. Former enemies became allies in new configurations that would have surprised participants in 1945. Germany and Japan rebuilt as democratic economic powers. The United Nations sought to channel international rivalry into institutions rather than battlefield confrontation, with mixed success. Memory of the war varies by nation, yet shared recognition of its horror continues to inform education, diplomacy, and efforts to prevent genocide.

To study World War II is to confront fundamental questions about human nature, political responsibility, and the limits of military force. It reminds us that indifference to aggression abroad can invite disaster at home, that propaganda and hatred can normalize atrocity, and that alliances among unlike partners can nonetheless achieve necessary ends. It also shows that recovery after devastation is possible when societies commit to reconstruction, accountability, and the rule of law. This comprehensive history has traced the war's arc from origins through theaters of battle, home fronts, crimes against humanity, technological innovation, diplomacy, and legacy. The story remains essential reading for anyone who seeks to understand the world we inherited from 1945 and the enduring obligation to build a peace worthy of those who sacrificed to achieve it.

Readers who finish this account should carry forward more than a list of battles and dates. They should remember that history is written from evidence left by the living and the dead, and that new archives continue to revise our understanding of decisions made under pressure. They should recognize that veterans, survivors, and descendants of victims each hold pieces of truth that no single narrative fully contains. World War II teaches that freedom and security require vigilance, that international institutions need constant renewal, and that the words "never again" demand action rather than sentiment. In honoring the past with accurate memory, we serve the future as well.
"""


def build(output_path: Path) -> int:
    lines = ["# World War II: A Comprehensive History", ""]
    for heading, body in SECTIONS:
        lines.append(f"## {heading}")
        combined = body.strip()
        if heading in EXPANSIONS:
            combined += "\n\n" + EXPANSIONS[heading].strip()
        lines.append(combined)
        lines.append("")

    lines.append(CONCLUSION.strip())
    lines.append("")

    text = "\n".join(lines)
    output_path.write_text(text, encoding="utf-8")
    return len(text.split())


def main() -> None:
    out = Path(__file__).resolve().parent.parent / "ww2-content.md"
    words = build(out)
    print(f"Wrote {out}")
    print(f"Words: {words}")


if __name__ == "__main__":
    main()
